source "https://rubygems.org"
gem 'jekyll-environment-variables'
gem 'jekyll-paginate'
gem "webrick", "~> 1.7"
gem "jekyll", "~> 3.9.5"
gem 'kramdown-parser-gfm'
#gem "github-pages", "~> 231", group: :jekyll_plugins
